### ISSUE TITLE
GDI Spec Compliance

### ISSUE THREAD

**Issue by tsloughter-splunk** [signalfx/splunk-otel-ruby#31]
Opening here before we open this same issue in the gdi spec repo to seek approval for a GA release.

- [X] Has an appropriate [maintainers team](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#teams).
- [X] [Permissions](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#permissions) set correctly.
- [X] [Branch protection](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#branch-protection) in place.
- [X] [Dependencies](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#dependencies) appropriately locked down.
- [X] [GitHub Applications](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#github-applications) set up per spec. 
- [X] Follows the [configuration requirements](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/configuration.md), if appropriate.
- [X] Follows the [semantic convention requirements](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/semantic_conventions.md), if appropriate.
- [X] [Required Files](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#required-files) in place.
  - [X] CHANGELOG.md
  - [X] CODE_OF_CONDUCT.md
  - [X] CONTRIBUTING.md
  - [X] .github/CODEOWNERS
  - [X] LICENSE
  - [X] README.md
    - [X] Build status badge
    - [X] Getting started
    - [X] Troubleshooting
    - [X] Link to official Splunk docs
    - [X] License information
  - [X] SECURITY.md
- [X] [Releases](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#github-releases) done to spec.
- [X] Type specific requirements (remove what doesn't apply)
  - [X] [Instrumentation Library](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#instrumentation-libraries)
    - [X] Documents all supported configuration parameters.
    - [X] Documents how to configure manual instrumentation.
    - [X] Documents how to configure log correlation.
    - [X] Documents minimum supported version of each auto-instrumentation framework.
  - [X] [Real User Monitoring Library](https://github.com/signalfx/gdi-specification/blob/v1.3.0/specification/repository.md#real-user-monitoring-libraries)
    - [X] Documents all supported configuration parameters.
    - [X] Documents how to configure manual instrumentation.
    - [X] Documents supported instrumentation.
    - [X] Documents supported platforms.

**Comment by pellared** [comment]
> MUST lock the versions of all build dependencies (e.g. libraries, binaries, scripts, docker images) or vendor them; EXCEPTION: tools that are available out-of-the-box

In my opinion, this requirement is not satisfied.

**Comment by tsloughter-splunk** [comment]
If that is the case can I open a PR on GDI Spec to say, "all build, test and example dependencies"? I interpreted "build" to only mean the deps needed to build the gem (those listed in gemspec), which are locked in Gemlock.

**Comment by pellared** [comment]
@tsloughter-splunk Works for me 👍

**Comment by pellared** [comment]
I created an issue for tracking and easier discussion https://github.com/signalfx/splunk-otel-ruby/issues/39

**Comment by pellared** [comment]
All issues solved
