### ISSUE TITLE
[GDI Spec] Possible inconsistency in docs

### ISSUE THREAD

**Issue by pellared** [signalfx/splunk-otel-ruby#46]
What is the difference between "unset" and "`""`" which we can see here:

https://github.com/signalfx/splunk-otel-ruby/blob/840209626ae26b7ea8ff071590225282dd253081/docs/advanced-config.md?plain=1#L48-L52

I suggest using "unset" everywhere or leaving it empty.

Moreover please make sure that:

> The SDK MUST interpret an empty value of an environment variable the same way as when the variable is unset.

Source: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#parsing-empty-value

**Comment by tsloughter-splunk** [comment]
The reason I listed it that way is because the gdi-spec says `Distribution MUST be unset "" (unlimited) for all others (not OpenTelemetry default)` and `""` is treated as unset. But I agree should be `unset` to not be potentially confusing, so updating in a PR.
