### ISSUE TITLE
[GDI Spec] Releases done to spec

### ISSUE THREAD

**Issue by pellared** [signalfx/splunk-otel-ruby#51]
Unable to verify before there is any beta release.

**Comment by pellared** [comment]
Checking https://github.com/signalfx/splunk-otel-ruby/releases/tag/untagged-4e9c5ca15e9c2fd16bdb

> MUST state version of OpenTelemetry repository built against if applicable

Also, it misses any information (usually copied from changelog)

**Comment by tsloughter-splunk** [comment]
Release 0.2.0 has been created.

**Comment by pellared** [comment]
1. The release is not public (it is not published)
2. "MUST state version of OpenTelemetry repository built against if applicable" is still not met. I think it is a good practice to copy the content from the changelog.

**Comment by pellared** [comment]
https://github.com/signalfx/splunk-otel-ruby/releases/tag/v0.2.0 is fine. Can you cleanup other draft releases?
